### ISSUE TITLE
Connection calls Connection.call() in exec_command(), which does not exist

### ISSUE THREAD

**Issue by ti-mo** [dw/mitogen#357] opened 2018-09-10 15:17 UTC
Hi David,

I'm trying to get a custom shell wrapper module to work with Mitogen, but the remote plugin tries to call `Connection.call()` from `Connection.exec_command()`, which is not defined locally, nor inherited from ConnectionBase. I believe this is an oversight on the Mitogen side, because I can't find `call()` in the `ansible/ansible` history, and it doesn't look like it's part of the `ConnectionBase` API contract.

Mitogen: `master`
Target: CentOS7/py2.7.5
Controller: Arch/py3.7.0
Ansible 2.6.4

```
The full traceback is:
Traceback (most recent call last):
  File "/home/xyz/.virtualenvs/ansible/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 105, in run
    item_results = self._run_loop(items)
  File "/home/xyz/.virtualenvs/ansible/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 337, in _run_loop
    res = self._execute(variables=task_vars)
  File "/home/xyz/.virtualenvs/ansible/lib/python3.7/site-packages/ansible/executor/task_executor.py", line 584, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/xyz/mitogen/ansible_mitogen/mixins.py", line 116, in run
    return super(ActionModuleMixin, self).run(tmp, task_vars)
  File "/home/xyz/action_plugins/helm_deploy.py", line 38, in inner
    rdict = func(*args, **kwargs)
  File "/home/xyz/action_plugins/helm_deploy.py", line 158, in run
    cache_path = self._make_cache_path(chart=local_chart_name)
  File "/home/xyz/action_plugins/helm_deploy.py", line 240, in _make_cache_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/home/xyz/mitogen/ansible_mitogen/mixins.py", line 382, in _low_level_execute_command
    mitogen_chdir=chdir,
  File "/home/xyz/mitogen/ansible_mitogen/connection.py", line 792, in exec_command
    rc, stdout, stderr = self.call(
AttributeError: 'Connection' object has no attribute 'call'
fatal: [ip-10-123-45-67.eu-west-1.compute.internal]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

I've looked at `exec_command` upstream before, and they go through a lot of effort to safely execute commands and handle stdio, buffering, prompt detection, etc. Is this something we can re-use?

**Comment by dw** [comment] 2018-09-10 16:09
Hi ti-mo,

Sorry about that, I merged a ton of stuff down yesterday (0.2.3 coming real soon) only to discover that exce_command() wasn't covered by CI. There is a new test for it now, and the problem is fixed. I've merged my branch back down to master again.

Do a git pull and the problem should be gone :)

Thanks for letting me know!

**Closed by dw** 2018-09-10 16:09 UTC

**Comment by dw** [comment] 2018-09-10 16:10
Note there are still some crazy CI failures I need to fix, although the Debops test jobs are running to completion. The failures look like broken tests, but I have still to investigate that later this evening.

**Comment by dw** [comment] 2018-09-12 14:09
Hi @ti-mo , the master branch is still in a bad state of health, and I can't revert the changes I've merged already without creating a permanent mess.

Please consider running from dmw branch, or referring to 'git reflog' to see the previous version you were on.

Hopefully this will be solved in the coming days.. there are quite a few issues introduced by recent work.

**Comment by dw** [comment] 2018-09-13 13:56
Yes, it's coming real soon, but I keep finding new reasons to delay it. CI has been in bad shape one way or another since the start of the stable series, and I really don't want another release where it's not 100% passing every time. That's produced a few big bugs already, and I'm certain at least one of them affects more than just CI

**Comment by ti-mo** [comment] 2018-09-13 15:08
Don't worry, the current gains are already _very_ promising, integrating with the Ansible runtime this closely is just tricky and full of traps. We're even seeing speedups running against `localhost`.. :)

Just take your time to polish things and push it out when ready, having a strong test suite pays off dividends when upstream (inevitably) breaks things one day and CI notifies you before the users do.
