### ISSUE TITLE
The Mitogen master process was unable to serve 'ansible.module_utils.distro._distro'

### ISSUE THREAD

**Issue by julian-klode** [dw/mitogen#622] opened 2019-08-15 22:13 UTC
Please drag-drop large logs as text file attachments.

[ansible.log](https://github.com/dw/mitogen/files/3507343/ansible.log)

* Which version of Ansible are you running?
  2.8.3+dfsg-1 from Ubuntu 19.10
* Is your version of Ansible patched in any way? 
  Debian patches
* Are you running with any custom modules, or `module_utils` loaded? 
  Not that I know

* Have you tried the latest master version from Git?
  Yes

* Do you have some idea of what the underlying problem may be?
  No
* Mention your host and target OS and versions
  Ubuntu 19.10 host, Ubuntu 18.04 target
* Mention your host and target Python versions
  3.7.4 and 3.6.8

* output of "ansible-config dump --only-changed".
  ```
  DEFAULT_STRATEGY(/home/jak/.ansible.cfg) = mitogen_linear
  DEFAULT_STRATEGY_PLUGIN_PATH(/home/jak/.ansible.cfg) = 
  ['/home/jak/Projects/Temporary/mitogen/ansible_mitogen/plugins/strategy']
  ```

**Comment by dw** [comment] 2019-08-15 22:14
Working on it right now :) Duplicate of #590. Please subscribe to that bug instead, it's the last before 0.2.8 will be cut. Thanks for reporting this!

**Closed by dw** 2019-08-15 22:14 UTC

**Comment by dw** [comment] 2019-08-17 21:30
This is now on master. Once again thank you for reporting it
