### ISSUE TITLE
Error after restarted firewall service (CentOS 7, firewalld)

### ISSUE THREAD

**Issue by iredmail** [dw/mitogen#562] opened 2019-03-12 04:25 UTC
- Ansible version: 2.7.8 (No patch or custom modules)
- Target OS: CentOS 7, Python 2.7.5

There's a task to restart firewalld service, but SSH port number wasn't changed. After restarted, mitogen failed with error message below:

> 2019-03-12 02:49:40,321 server fatal: [test.io]: UNREACHABLE! => {"changed": false, "msg": "Mitogen was disconnected from the remote environment while a call was in-progress. If you feel this is in error, please file a bug. __Original error was: the respondent Context has disconnected__", "unreachable": true}

**Comment by iredmail** [comment] 2019-03-12 04:33
A quick update: we got this error few times with same target server, triggered by different tasks.
I'm not sure whether it's caused by slow/unstable ssh or network connection, had to disable mitogen temporarily to make the deployment stable enough for clients. :(

**Comment by dw** [comment] 2019-08-17 22:44
Apologies for the huge delay replying to this, it appears to be a duplicate of #570 which was fixed in 0.2.7. Please reopen if you are still encountering difficulties.

Thanks a ton for reporting this!

**Closed by dw** 2019-08-17 22:44 UTC
Labels: ansible, user-reported
