### ISSUE TITLE
ansible: ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by sharph** [dw/mitogen#249] opened 2018-05-14 16:10 UTC
Thanks for your help with #179. mitogen is awesome when it works. We're now trying to scale to > 100 targets and running into the following traceback. Any ideas?

[log.txt](https://github.com/dw/mitogen/files/2003077/log.txt)

**Comment by dw** [comment] 2018-05-14 16:25
Can you give me some hints about your environment btw (controller OS, target OS, eventual total number of targets)

**Comment by sharph** [comment] 2018-05-14 16:53
I'm running ansible in a docker container running inside a Ubuntu 14.04 host. Target OS varies, but all Ubuntu based. I'd like to hit between 100-200 targets.

There is definitely slowdown, which seems to resolve somewhat when `MITOGEN_POOL_SIZE` is increased. (This error is still raised when I leave `MITOGEN_POLL_SIZE` undefined.) We have role/task profiling turned on but no real numbers to show since the playbook doesn't complete.

**Comment by sharph** [comment] 2018-05-14 16:55
Python 2.7.12 inside of the container

**Comment by dw** [comment] 2018-05-14 17:53
If you check out 'dmw' branch, there is an epoll implementation that is automatically selected for masters now. Children don't yet know how to swap out their implementation.

The tests are failing due to a hang, so buyer beware :)  This may take a few days to cook.

**Comment by sharph** [comment] 2018-05-14 19:38
It got much farther, but then I started seeing errors like the following:

```
ERROR! [pid 18] 19:29:52.640100 E mitogen: While invoking ContextService().dispatch()
Traceback (most recent call last):
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 211, in on_receive_message
    response = self._on_receive_message(msg)
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 198, in _on_receive_message
    ret = method(**kwargs)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 309, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 260, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1240, in ssh
    return self.connect('ssh', **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1198, in connect
    return self._connect(klass, name=name, **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1180, in _connect
    stream.connect()
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 143, in connect
    super(Stream, self).connect()
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 919, in connect
    self._connect_bootstrap(extra_fd)
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 182, in _connect_bootstrap
    for buf in it:
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 390, in iter_read
    rfds, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()
ERROR! [pid 5617] 19:29:52.650874 E mitogen: _broker_main() force disconnecting <Side of Waker(Broker(0x7fb741b42590) rfd=None, wfd=None) fd None>

TASK [REDACTEDREDACTED] **************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     rfds, _, _ = select.select(fds, [], [], timeout)
fatal: [server-13.serverfarm.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
ERROR! [pid 18] 19:29:53.073606 E mitogen: While invoking ContextService().dispatch()
Traceback (most recent call last):
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 211, in on_receive_message
    response = self._on_receive_message(msg)
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 198, in _on_receive_message
    ret = method(**kwargs)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 309, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 260, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1240, in ssh
    return self.connect('ssh', **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1198, in connect
    return self._connect(klass, name=name, **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1180, in _connect
    stream.connect()
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 143, in connect
    super(Stream, self).connect()
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 919, in connect
    self._connect_bootstrap(extra_fd)
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 182, in _connect_bootstrap
    for buf in it:
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 390, in iter_read
    rfds, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()
ERROR! [pid 5622] 19:29:53.082219 E mitogen: _broker_main() force disconnecting <Side of Waker(Broker(0x7fb7430af490) rfd=None, wfd=None) fd None>
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     rfds, _, _ = select.select(fds, [], [], timeout)
fatal: [server-14.serverfarm.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
ERROR! [pid 18] 19:29:53.574520 E mitogen: While invoking ContextService().dispatch()
Traceback (most recent call last):
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 211, in on_receive_message
    response = self._on_receive_message(msg)
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 198, in _on_receive_message
    ret = method(**kwargs)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 309, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 260, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1240, in ssh
    return self.connect('ssh', **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1198, in connect
    return self._connect(klass, name=name, **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1180, in _connect
    stream.connect()
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 143, in connect
    super(Stream, self).connect()
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 919, in connect
    self._connect_bootstrap(extra_fd)
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 182, in _connect_bootstrap
    for buf in it:
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 390, in iter_read
    rfds, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()
ERROR! [pid 5627] 19:29:53.586582 E mitogen: _broker_main() force disconnecting <Side of Waker(Broker(0x7fb73f205190) rfd=None, wfd=None) fd None>
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     rfds, _, _ = select.select(fds, [], [], timeout)
fatal: [server-15.serverfarm.com]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

ERROR! [pid 18] 19:29:54.025592 E mitogen: While invoking ContextService().dispatch()
Traceback (most recent call last):
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 211, in on_receive_message
    response = self._on_receive_message(msg)
  File "/docker-container/ansible/mitogen-master/mitogen/service.py", line 198, in _on_receive_message
    ret = method(**kwargs)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 309, in _wait_or_start
    response = self._connect(key, spec, via=via)
  File "/docker-container/ansible/mitogen-master/ansible_mitogen/services.py", line 260, in _connect
    context = method(via=via, unidirectional=True, **spec['kwargs'])
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1240, in ssh
    return self.connect('ssh', **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1198, in connect
    return self._connect(klass, name=name, **kwargs)
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 1180, in _connect
    stream.connect()
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 143, in connect
    super(Stream, self).connect()
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 919, in connect
    self._connect_bootstrap(extra_fd)
  File "/docker-container/ansible/mitogen-master/mitogen/ssh.py", line 182, in _connect_bootstrap
    for buf in it:
  File "/docker-container/ansible/mitogen-master/mitogen/parent.py", line 390, in iter_read
    rfds, _, _ = select.select(fds, [], [], timeout)
ValueError: filedescriptor out of range in select()
```

**Comment by dw** [comment] 2018-05-14 19:57
Oh man select sucks so much. I need to update iter_read() and friends too. It's not a limit on the number of descriptors, it's a limit on the maximum integer file descriptor :)

Leave this for now and I'll spin up some GCE jobs to test further. Thanks for your help so far!

**Comment by dw** [comment] 2018-05-15 00:53
Hi Sharp,

I'd appreciate it if you gave this another quick test. All the FD limits should be entirely gone for non-connection-delegation cases (i.e. vanilla Ansible style direct controller->target connections).

I saw one new interesting race condition in the tests, but it may be unrelated, and I haven't been able to reproduce it so far.

**Comment by sharph** [comment] 2018-05-15 18:01
Playbook now completes without error. There is a lot of room for improvement where performance is concerned. The playbook completed in a little more than twice the time as regular ansible.

**Comment by sharph** [comment] 2018-05-15 18:02
No local actions in this playbook.

**Comment by dw** [comment] 2018-05-15 18:10
Yikes, it is twice as slow as vanilla?

**Comment by sharph** [comment] 2018-05-15 19:56
That's correct, unfortunately.

**Comment by dw** [comment] 2018-05-15 20:02
Hi Sharp,

I'm closing this ticket off and opening #250 to track scaling work. That will take some time, I need to set up a representative load test (probably DebOps) rather than just running task loops.

Thanks so much for the feedback, and the focus to get this piece of the puzzle solved. :)

**Closed by dw** 2018-05-15 20:02 UTC

**Comment by sharph** [comment] 2018-05-15 20:12
Sure thing! Welcome and thanks!

**Comment by anyouuu** [comment] 2024-11-15 13:05
I am using the ansbile runner 2.2.2 package and also encountered this problem. How did you solve it?
